// ? FETCH BLOGS SECTION 
export const FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE';
// ? END OF FETCH BLOGS SECTION

// ! DELETE BLOG SECTION
export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';
// ! END OF DELETE BLOG SECTION

// * ADD BLOG SECTION
export const ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_FAILURE = 'ADD_BLOG_FAILURE';
// * END OF ADD BLOG SECTION


// * search blog section

export const SEARCH_BLOG_REQUEST = 'SEARCH_BLOG_REQUEST';


// * end of search blog section

// * update blog section

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE';
